// plan9asmgenregs regenerates the physical ARM64 system-register grammar
// from the selected Go assembler, without depending on GOROOT at runtime.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
)

func generateSystemRegisters(source []byte) ([]byte, error) {
	rows := regexp.MustCompile(`\{"([A-Za-z0-9_]+)", REG_\w+, (0x[0-9a-f]+), ([^}]+)\}`).FindAllSubmatch(source, -1)
	if len(rows) == 0 {
		return nil, fmt.Errorf("Go system-register table contains no recognized rows")
	}
	if len(rows) != bytes.Count(source, []byte(`{"`)) {
		return nil, fmt.Errorf("Go system-register table contains unrecognized rows; refusing a partial grammar")
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by plan9asmgenregs from the Go assembler system-register table. DO NOT EDIT.\n\npackage plan9asm\n\n")
	output.WriteString("var arm64GoSystemRegisters = map[string]arm64SystemRegisterSpec{\n")
	seen := make(map[string]bool)
	for _, row := range rows {
		name := string(row[1])
		if seen[name] {
			return nil, fmt.Errorf("duplicate system register %q", name)
		}
		seen[name] = true
		encoding, err := strconv.ParseUint(string(row[2]), 0, 32)
		if err != nil || encoding&^uint64(0x1fffe0) != 0 || encoding == 0 {
			return nil, fmt.Errorf("invalid system-register encoding %q", row[2])
		}
		flags := strings.ReplaceAll(string(row[3]), " ", "")
		if flags != "SR_READ" && flags != "SR_WRITE" && flags != "SR_READ|SR_WRITE" {
			return nil, fmt.Errorf("invalid access flags %q for %s", flags, name)
		}
		fmt.Fprintf(&output, "%q: {encoding: %#x, readable: %t, writable: %t},\n",
			name, (encoding>>5)&0x7fff, strings.Contains(flags, "SR_READ"), strings.Contains(flags, "SR_WRITE"))
	}
	output.WriteString("}\n")
	return format.Source(output.Bytes())
}

func main() {
	root := flag.String("goroot", runtime.GOROOT(), "Go toolchain containing the authoritative assembler table")
	output := flag.String("out", "arm64_sysregs_generated.go", "generated Go source file")
	flag.Parse()
	if flag.NArg() != 0 {
		fmt.Fprintln(os.Stderr, "unexpected positional arguments")
		os.Exit(2)
	}
	source, err := os.ReadFile(filepath.Join(*root, "src", "cmd", "internal", "obj", "arm64", "sysRegEnc.go"))
	if err == nil {
		var generated []byte
		generated, err = generateSystemRegisters(source)
		if err == nil {
			err = os.WriteFile(*output, generated, 0o644)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
