package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/xgo-dev/plan9asm"
)

// These packages are generated by this test and contain no imports or init.
// Their archive symbol tables observe cmd/go's real preprocessing separately
// from direct cmd/asm and the translator's preprocessing.
func TestAssemblerProfilesActualDriverCPUFiveArchitectures(t *testing.T) {
	goBinary, err := exec.LookPath("go")
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct {
		target, key, value string
		want               []string
	}{
		{"linux/386", "GO386", "sse2", []string{"GO386_sse2"}},
		{"linux/386", "GO386", "softfloat", []string{"GO386_softfloat"}},
		{"linux/amd64", "GOAMD64", "v1", []string{"GOAMD64_v1"}},
		{"linux/amd64", "GOAMD64", "v3", []string{"GOAMD64_v3"}},
		{"linux/amd64", "GOAMD64", "v4", []string{"GOAMD64_v4"}},
		{"linux/arm", "GOARM", "5", []string{"GOARM_5"}},
		{"linux/arm", "GOARM", "6", []string{"GOARM_6", "GOARM_5"}},
		{"linux/arm", "GOARM", "7,hardfloat", []string{"GOARM_7", "GOARM_6", "GOARM_5"}},
		{"linux/arm64", "GOARM64", "", nil},
		{"linux/arm64", "GOARM64", "v8.0,crypto", nil},
		{"linux/arm64", "GOARM64", "v8.0,lse", []string{"GOARM64_LSE"}},
		{"linux/arm64", "GOARM64", "v8.1", []string{"GOARM64_LSE"}},
		{"linux/arm64", "GOARM64", "v9.1", []string{"GOARM64_LSE"}},
		{"js/wasm", "GOWASM", "satconv,signext", nil},
	} {
		t.Run(tc.target+"/"+tc.value, func(t *testing.T) {
			// The fixture itself runs under the chosen local Go toolchain.
			// Older Go rejects the floating-point option rather than selecting
			// a different CPU level; keep that boundary explicit.
			testMinor, err := discoveryGoMinor(runtime.Version())
			if err != nil {
				t.Fatal(err)
			}
			if tc.key == "GOARM" && testMinor < 22 {
				tc.value = strings.Split(tc.value, ",")[0]
				tc.want = nil
			}
			ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
			defer cancel()
			env := replaceEnv(targetFeatureTestEnv(), map[string]string{tc.key: tc.value, "GOEXPERIMENT": "fieldtrack"})
			baseline, err := captureDiscoveryTargetFeatures(ctx, goBinary, t.TempDir(), env, tc.target, nil)
			if err != nil {
				t.Fatal(err)
			}
			minor, _ := discoveryGoMinor(baseline.GoVersion)
			if strings.HasPrefix(tc.target, "linux/arm64") && minor < 23 && tc.value != "" {
				// The actual Go1.20 driver does not implement this knob. Its
				// baseline still participates; it cannot prove explicit v8/v9.
				if baseline.Environment[tc.key] != "" {
					t.Fatal("pre-GOARM64 driver reported an explicit feature")
				}
				return
			}
			parts := strings.Split(tc.target, "/")
			defines, err := plan9asm.GoAssemblerDefinesForEnvironment(parts[0], parts[1], baseline.Environment)
			want := append([]string{"GOOS_" + parts[0], "GOARCH_" + parts[1]}, tc.want...)
			if err != nil || !reflect.DeepEqual(defines, want) {
				t.Fatalf("explicit profile macros = %v, %v; source-audited expectation %v", defines, err, want)
			}
			// Observe GOROOT with this exact driver, not with host build.Default.
			rootData, _, err := runDiscoveryMachineCommand(ctx, t.TempDir(), env, goBinary, "env", "GOROOT")
			if err != nil {
				t.Fatal(err)
			}
			root := strings.TrimSpace(string(rootData))
			fixture := t.TempDir()
			const packagePath = "example.invalid/plan9asm-assembler-macros"
			macros := []string{"GOOS_linux", "GOOS_js", "GOOS_windows", "GOARCH_386", "GOARCH_amd64", "GOARCH_arm", "GOARCH_arm64", "GOARCH_wasm", "GO386_sse2", "GO386_softfloat", "GOAMD64_v1", "GOAMD64_v2", "GOAMD64_v3", "GOAMD64_v4", "GOARM_5", "GOARM_6", "GOARM_7", "GOARM64_LSE", "GOWASM_satconv", "GOWASM_signext", "GOEXPERIMENT_fieldtrack"}
			source := "#include \"textflag.h\"\nTEXT ·Probe(SB),NOSPLIT,$0-0\nRET\n"
			for index, macro := range macros {
				source += fmt.Sprintf("#ifdef %s\nGLOBL ·marker%03d(SB),NOPTR,$8\nDATA ·marker%03d(SB)/8,$1\n#endif\n", macro, index, index)
			}
			for name, data := range map[string]string{"go.mod": "module " + packagePath + "\n\ngo 1.20\n", "probe.go": "package macros\n\nfunc Probe()\n", "probe.s": source} {
				if err := os.WriteFile(filepath.Join(fixture, name), []byte(data), 0600); err != nil {
					t.Fatal(err)
				}
			}
			actualEnv := replaceEnv(env, baseline.Environment)
			listData, _, err := runDiscoveryMachineCommand(ctx, fixture, actualEnv, goBinary, "list", "-export", "-json", "-mod=readonly", ".")
			if err != nil {
				t.Fatal(err)
			}
			var pkg struct {
				ImportPath, Export string
				Standard           bool
				SFiles             []string
			}
			if err := json.Unmarshal(listData, &pkg); err != nil || pkg.ImportPath != packagePath || pkg.Standard || pkg.Export == "" || !reflect.DeepEqual(pkg.SFiles, []string{"probe.s"}) {
				t.Fatalf("unexpected actual Go package selection: %+v, %v", pkg, err)
			}
			nativeNM, _, err := runDiscoveryMachineCommand(ctx, fixture, actualEnv, goBinary, "tool", "nm", pkg.Export)
			if err != nil {
				t.Fatal(err)
			}
			object := filepath.Join(t.TempDir(), "probe.o")
			args := []string{"tool", "asm", "-p", packagePath, "-I", filepath.Join(root, "pkg/include"), "-o", object}
			for _, define := range defines {
				args = append(args, "-D", define)
			}
			args = append(args, filepath.Join(fixture, "probe.s"))
			if _, _, err := runDiscoveryMachineCommand(ctx, fixture, actualEnv, goBinary, args...); err != nil {
				t.Fatal(err)
			}
			directNM, _, err := runDiscoveryMachineCommand(ctx, fixture, actualEnv, goBinary, "tool", "nm", object)
			if err != nil {
				t.Fatal(err)
			}
			arch := map[string]plan9asm.Arch{"386": plan9asm.ArchAMD64, "amd64": plan9asm.ArchAMD64, "arm": plan9asm.ArchARM, "arm64": plan9asm.ArchARM64, "wasm": plan9asm.ArchWASM}[parts[1]]
			parsed, err := plan9asm.ParseWithDefines(arch, source, defines)
			if err != nil {
				t.Fatal(err)
			}
			for index, macro := range macros {
				name := fmt.Sprintf("marker%03d", index)
				want := containsTargetFeature(defines, macro)
				parserSelected := false
				for _, global := range parsed.Globl {
					parserSelected = parserSelected || strings.Contains(global.Sym, name)
				}
				if strings.Contains(string(nativeNM), name) != want || strings.Contains(string(directNM), name) != want || parserSelected != want {
					t.Errorf("%s: native=%t direct=%t translator=%t want=%t", macro, strings.Contains(string(nativeNM), name), strings.Contains(string(directNM), name), parserSelected, want)
				}
			}
			t.Logf("actual %s %s env=%v package=%s role=ordinary_external macros=%v source_sha=%s native_nm_sha=%s direct_nm_sha=%s", baseline.GoVersion, tc.target, baseline.Environment, pkg.ImportPath, defines, discoveryFeatureBytesSHA256([]byte(source)), discoveryFeatureBytesSHA256(nativeNM), discoveryFeatureBytesSHA256(directNM))
		})
	}
}
