package gotoolprofile

import (
	"reflect"
	"strings"
	"testing"
)

func TestGeneratedHeaderDefinitionsPreserveValuesAndPresence(t *testing.T) {
	header := []byte("// generated by compiler\n#define const_String \"x y\\n\"\n#define const_Huge 123456789012345678901234567890\n#define Layout__size 48\n")
	defs, err := HeaderDefinitions(header)
	if err != nil {
		t.Fatal(err)
	}
	wanted := map[string]string{"const_String": `"x y\n"`, "const_Huge": "123456789012345678901234567890", "Layout__size": "48"}
	if !reflect.DeepEqual(defs, wanted) {
		t.Fatalf("complete definitions = %v, want %v", defs, wanted)
	}
	reordered, err := HeaderDefinitions([]byte("// a different formatter\n#define Layout__size\t48\n#define const_Huge 123456789012345678901234567890\n#define const_String \"x y\\n\"\n"))
	if err != nil || HeaderDefinitionSHA256(defs) != HeaderDefinitionSHA256(reordered) {
		t.Fatalf("format-only difference changed canonical definitions: %v", err)
	}
	for _, changed := range []map[string]string{
		{"const_String": `"x y\n"`, "const_Huge": "123456789012345678901234567890"},
		{"const_String": `"x y\n"`, "const_Huge": "123456789012345678901234567890", "Layout__size": "49"},
		{"const_String": `"x y\n"`, "const_Huge": "123456789012345678901234567890", "Layout__size": "48", "const_Fraction": "1.25"},
	} {
		if HeaderDefinitionSHA256(defs) == HeaderDefinitionSHA256(changed) {
			t.Fatal("value, omission or additional presence was ignored")
		}
	}
	if HeaderDefinitionSHA256(nil) != HeaderDefinitionSHA256(map[string]string{}) {
		t.Fatal("an empty definition map did not survive JSON omitempty normalization")
	}
}

func TestGeneratedHeaderDefinitionsRejectUnsupportedAndAmbiguousInput(t *testing.T) {
	for _, source := range []string{
		"#define DUP 1\n#define DUP 1\n", "#define FUNC(x) x\n", "#define EMPTY\n",
		"#include \"fake.h\"\n", "#ifdef MISSING\n#endif\n", "TEXT Fake(SB),$0-0\n",
		"#define BAD-NAME 1\n", "#define X 1\\\n+2\n", "/* hidden */\n", "#define X 1\x00\n",
	} {
		t.Run(strings.ReplaceAll(source, "\n", "_"), func(t *testing.T) {
			if _, err := HeaderDefinitions([]byte(source)); err == nil {
				t.Fatal("unrecognized compiler header syntax was silently accepted")
			}
		})
	}
}

func TestCanonicalGeneratedHeaderRetainsExactFullDefinitions(t *testing.T) {
	definitions := map[string]string{"Layout__size": "48", "const_String": `"x y\n"`, "const_Huge": "123456789012345678901234567890"}
	data, err := CanonicalGeneratedHeader(definitions)
	if err != nil {
		t.Fatal(err)
	}
	actual, err := HeaderDefinitions(data)
	if err != nil || !reflect.DeepEqual(actual, definitions) {
		t.Fatalf("canonical effective header changed values/presence: %s: %v", data, err)
	}
	if _, err := CanonicalGeneratedHeader(nil); err == nil {
		t.Fatal("missing definitions became an empty generated input")
	}
	for _, bad := range []map[string]string{{"Bad-Name": "1"}, {"NAME": ""}, {"NAME": "1\n#define OTHER 2"}, {"NAME": "1\\"}} {
		if _, err := CanonicalGeneratedHeader(bad); err == nil {
			t.Fatal("noncanonical definitions became generated source bytes")
		}
	}
}
