package main

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/xgo-dev/plan9asm/internal/gotoolprofile"
)

func TestGeneratedHeaderProductionConsumerRecompilesAndConsumesFullHeader(t *testing.T) {
	repo, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	input, dir := generatedHeaderFixture(t, "linux/amd64")
	source := "#include \"go_asm.h\"\n#ifndef const_Fraction\n#include \"textflag.h\"\n#endif\n#ifdef const_Fraction\n#include \"missing-inactive.h\"\n#endif\nTEXT ·Probe(SB),NOSPLIT,$0-0\nMOVQ $const_Imported, AX\nMOVQ $Layout_Last, CX\nRET\n"
	file := filepath.Join(dir, input.AsmFiles[0])
	if err := os.WriteFile(file, []byte(source), 0600); err != nil {
		t.Fatal(err)
	}
	input.Sources[input.AsmFiles[0]], input.Headers[input.AsmFiles[0]] = featureBytesSHA256([]byte(source)), source
	root := runtime.GOROOT()
	toolFile := "pkg/include/textflag.h"
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(toolFile)))
	if err != nil {
		t.Fatal(err)
	}
	input.ToolSources = map[string]string{toolFile: featureBytesSHA256(data)}
	t.Chdir(dir)
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	metadata, err := queryGeneratedHeaders(targetSpec{Goos: "linux", Goarch: "amd64"}, []string{"."}, nil, input.AsmFiles, input.Module, t.TempDir(), compileConfig{FeaturePath: writeFeatureInput(t, input), Context: ctx})
	if err != nil {
		t.Fatal(err)
	}
	input.GeneratedHeaders = metadata
	config, err := resolveCompileConfig(true, "", true, 0)
	if err != nil {
		t.Fatal(err)
	}
	config.FeaturePath, config.Context = writeFeatureInput(t, input), ctx
	report, _, err := runOneTarget(targetSpec{Goos: "linux", Goarch: "amd64"}, []string{"."}, nil, input.AsmFiles, input.Module, t.TempDir(), false, 0, true, false, true, repo, config)
	if err != nil || report.Success != 1 || report.Failed != 0 {
		t.Fatalf("real generated-header Go/CPP/LLVM consumption failed: %#v: %v", report, err)
	}
	proof := report.FeatureSelection
	if proof.GeneratedHeaders == nil || len(proof.GeneratedHeaders.Headers) != 1 || proof.CPP[0].Inputs["generated/"+input.Module+"/go_asm.h"] == "" {
		t.Fatalf("generated consumption lacks its independent actual compiler origin: %#v", proof)
	}
	if err := gotoolprofile.ValidateSelection(input, proof, nil, true); err != nil {
		t.Fatal(err)
	}
	canonical, err := json.Marshal(proof)
	if err != nil {
		t.Fatal(err)
	}
	for name, mutate := range map[string]func(*gotoolprofile.SelectionProof){
		"missing metadata": func(p *gotoolprofile.SelectionProof) { p.GeneratedHeaders = nil },
		"changed value": func(p *gotoolprofile.SelectionProof) {
			p.GeneratedHeaders.Headers[0].Definitions["const_Imported"] = "42"
		},
		"additional presence": func(p *gotoolprofile.SelectionProof) {
			p.GeneratedHeaders.Headers[0].Definitions["const_Fraction"] = "1.25"
		},
		"missing presence": func(p *gotoolprofile.SelectionProof) {
			delete(p.GeneratedHeaders.Headers[0].Definitions, "Layout_Last")
		},
		"import export": func(p *gotoolprofile.SelectionProof) {
			p.GeneratedHeaders.Headers[0].Imports[0].ExportSHA256 = strings.Repeat("0", 64)
		},
		"generated bytes": func(p *gotoolprofile.SelectionProof) {
			p.CPP[0].Inputs["generated/"+input.Module+"/go_asm.h"] = strings.Repeat("0", 64)
		},
		"source": func(p *gotoolprofile.SelectionProof) {
			p.GeneratedHeaders.Headers[0].CompiledGoSHA256["layout.go"] = strings.Repeat("0", 64)
		},
		"profile": func(p *gotoolprofile.SelectionProof) { p.GeneratedHeaders.ProfileID = strings.Repeat("0", 64) },
		"role":    func(p *gotoolprofile.SelectionProof) { p.GeneratedHeaders.Packages[0].SourceRole = "stdlib" },
	} {
		t.Run(name, func(t *testing.T) {
			var changed gotoolprofile.SelectionProof
			if err := json.Unmarshal(canonical, &changed); err != nil {
				t.Fatal(err)
			}
			mutate(&changed)
			if changed.GeneratedHeaders != nil {
				changed.GeneratedHeaders.Headers[0].DefinitionsSHA256 = gotoolprofile.HeaderDefinitionSHA256(changed.GeneratedHeaders.Headers[0].Definitions)
			}
			if err := gotoolprofile.ValidateSelection(input, &changed, nil, true); err == nil {
				t.Fatal("offline reader accepted mutated generated origin")
			}
		})
	}
	var formatted gotoolprofile.MetadataProof
	metadataJSON, err := json.Marshal(metadata)
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(metadataJSON, &formatted); err != nil {
		t.Fatal(err)
	}
	formatted.Headers[0].HeaderSHA256 = strings.Repeat("0", 64)
	formatted.Headers[0].ObjectSHA256 = strings.Repeat("1", 64)
	if err := gotoolprofile.ValidateGeneratedHeaderAgreement(input, metadata, &formatted, nil); err != nil {
		t.Fatalf("independently valid formatting-only compiler outputs disagreed: %v", err)
	}
}

func TestGeneratedHeaderProductionConsumerFiveArchitectures(t *testing.T) {
	repo, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	for _, target := range []string{"linux/amd64", "linux/386", "linux/arm", "linux/arm64", "js/wasm"} {
		t.Run(target, func(t *testing.T) {
			input, dir := generatedHeaderFixture(t, target)
			// cmd/go's earlier gensymabis invocation has an empty header;
			// do not require layout presence during that distinct phase.
			source := "#include \"go_asm.h\"\n#ifdef const_Fraction\n#include \"missing-inactive.h\"\n#endif\nTEXT ·Probe(SB),$0-0\nRET\n"
			if err := os.WriteFile(filepath.Join(dir, input.AsmFiles[0]), []byte(source), 0600); err != nil {
				t.Fatal(err)
			}
			input.Sources[input.AsmFiles[0]], input.Headers[input.AsmFiles[0]] = featureBytesSHA256([]byte(source)), source
			t.Chdir(dir)
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
			defer cancel()
			parts := strings.Split(target, "/")
			spec := targetSpec{Goos: parts[0], Goarch: parts[1]}
			input.GeneratedHeaders, err = queryGeneratedHeaders(spec, []string{"."}, nil, input.AsmFiles, input.Module, t.TempDir(), compileConfig{FeaturePath: writeFeatureInput(t, input), Context: ctx})
			if err != nil {
				t.Fatal(err)
			}
			config, err := resolveCompileConfig(true, "", true, 0)
			if err != nil {
				t.Fatal(err)
			}
			config.FeaturePath, config.Context = writeFeatureInput(t, input), ctx
			report, _, err := runOneTarget(spec, []string{"."}, nil, input.AsmFiles, input.Module, t.TempDir(), false, 0, true, false, true, repo, config)
			if err != nil || report.Success != 1 || report.Failed != 0 {
				t.Fatalf("full target header/object consumption failed: %#v: %v", report, err)
			}
			if err := gotoolprofile.ValidateSelection(input, report.FeatureSelection, nil, true); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestGeneratedHeaderProductionConsumerRejectsSelfConsistentProducerMutation(t *testing.T) {
	input, dir := generatedHeaderFixture(t, "linux/amd64")
	t.Chdir(dir)
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	metadata, err := queryGeneratedHeaders(targetSpec{Goos: "linux", Goarch: "amd64"}, []string{"."}, nil, input.AsmFiles, input.Module, t.TempDir(), compileConfig{FeaturePath: writeFeatureInput(t, input), Context: ctx})
	if err != nil {
		t.Fatal(err)
	}
	canonical, err := json.Marshal(metadata)
	if err != nil {
		t.Fatal(err)
	}
	for name, mutate := range map[string]func(*gotoolprofile.MetadataProof){
		"unused value":        func(p *gotoolprofile.MetadataProof) { p.Headers[0].Definitions["const_Huge"] = "7" },
		"missing presence":    func(p *gotoolprofile.MetadataProof) { delete(p.Headers[0].Definitions, "Layout_First") },
		"additional presence": func(p *gotoolprofile.MetadataProof) { p.Headers[0].Definitions["const_Fraction"] = "1.25" },
		"dependency export":   func(p *gotoolprofile.MetadataProof) { p.Headers[0].Imports[0].ExportSHA256 = strings.Repeat("0", 64) },
	} {
		t.Run(name, func(t *testing.T) {
			var changed gotoolprofile.MetadataProof
			if err := json.Unmarshal(canonical, &changed); err != nil {
				t.Fatal(err)
			}
			mutate(&changed)
			changed.Headers[0].DefinitionsSHA256 = gotoolprofile.HeaderDefinitionSHA256(changed.Headers[0].Definitions)
			input.GeneratedHeaders = &changed
			config := compileConfig{FeaturePath: writeFeatureInput(t, input), Context: ctx}
			_, _, err := runOneTarget(targetSpec{Goos: "linux", Goarch: "amd64"}, []string{"."}, nil, input.AsmFiles, input.Module, t.TempDir(), false, 0, true, false, true, "unused", config)
			if err == nil || !strings.Contains(err.Error(), "independent generated-header definitions/imports differ") {
				t.Fatalf("actual consumer accepted self-consistent altered metadata: %v", err)
			}
		})
	}
}

func TestFeatureCPPSourceOrderUsesPackageCWDAndOnlyActiveIncludes(t *testing.T) {
	input, dir := generatedHeaderFixture(t, "linux/amd64")
	files := map[string]string{
		"probe_amd64.s": "#include \"sub/outer.h\"\n#ifdef ABSENT\n#include \"missing-inactive.h\"\n#endif\nTEXT ·Probe(SB),$0-0\nMOVQ $CHOICE,AX\nRET\n",
		"sub/outer.h":   "#include \"choice.h\"\n",
		"choice.h":      "#define CHOICE 41\n",
		"sub/choice.h":  "#define CHOICE 99\n",
	}
	for name, source := range files {
		file := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(file), 0700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(file, []byte(source), 0600); err != nil {
			t.Fatal(err)
		}
		input.Sources[name] = featureBytesSHA256([]byte(source))
		if strings.HasSuffix(name, ".s") {
			input.Headers[name] = source
		}
	}
	input.Directories["."] = append(input.Directories["."], "choice.h", "sub")
	input.Directories["sub"] = []string{"choice.h", "outer.h"}
	sort.Strings(input.Directories["."])
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	canonicalDir, err := filepath.EvalSymlinks(dir)
	if err != nil {
		t.Fatal(err)
	}
	consumer := &featureConsumer{Input: input, Context: ctx, Dir: canonicalDir, Root: runtime.GOROOT()}
	asm := filepath.Join(dir, input.AsmFiles[0])
	expanded, sources, err := consumer.preprocessCPP(asm, input.Module, nil)
	if err != nil || !strings.Contains(string(expanded), "$41") || strings.Contains(string(expanded), "$99") || sources["module/choice.h"] == "" || sources["module/sub/choice.h"] != "" || len(sources) != 3 {
		t.Fatalf("source-order CPP ignored Go package-CWD or consumed inactive include: %s %v: %v", expanded, sources, err)
	}
	// The same original source must also compile under the actual Go driver;
	// this is not just agreement with a synthetic preprocessor model.
	t.Chdir(dir)
	_, err = queryGeneratedHeaders(targetSpec{Goos: "linux", Goarch: "amd64"}, []string{"."}, nil, input.AsmFiles, input.Module, t.TempDir(), compileConfig{FeaturePath: writeFeatureInput(t, input), Context: ctx})
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(asm, []byte("#include \"missing-active.h\"\nTEXT ·Probe(SB),$0-0\nRET\n"), 0600); err != nil {
		t.Fatal(err)
	}
	input.Sources[input.AsmFiles[0]] = featureBytesSHA256([]byte("#include \"missing-active.h\"\nTEXT ·Probe(SB),$0-0\nRET\n"))
	if _, _, err := consumer.preprocessCPP(asm, input.Module, nil); err == nil {
		t.Fatal("missing active include was silently consumed as an empty header")
	}
}

func TestGeneratedHeaderConsumerRetainsDependencyGuardUntilFinalObject(t *testing.T) {
	input, dir := generatedHeaderFixture(t, "linux/amd64")
	dep := t.TempDir()
	dependency := filepath.Join(dep, "layout.go")
	for name, source := range map[string]string{
		"go.mod":    "module example.invalid/external\n\ngo 1.24\n",
		"layout.go": "package external\ntype Layout struct { Word uintptr }\nfunc Body() int { return 1 }\n",
	} {
		if err := os.WriteFile(filepath.Join(dep, name), []byte(source), 0600); err != nil {
			t.Fatal(err)
		}
	}
	for name, source := range map[string]string{
		"go.mod":    "module example.invalid/header\n\ngo 1.24\nrequire example.invalid/external v1.0.0\nreplace example.invalid/external => " + filepath.ToSlash(dep) + "\n",
		"layout.go": "package header\nimport \"example.invalid/external\"\ntype Layout struct { Value external.Layout }\nfunc Probe()\n",
	} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(source), 0600); err != nil {
			t.Fatal(err)
		}
		input.Sources[name], input.Headers[name] = featureBytesSHA256([]byte(source)), source
	}
	t.Chdir(dir)
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	metadata, err := queryGeneratedHeaders(targetSpec{Goos: "linux", Goarch: "amd64"}, []string{"."}, nil, input.AsmFiles, input.Module, t.TempDir(), compileConfig{FeaturePath: writeFeatureInput(t, input), Context: ctx})
	if err != nil {
		t.Fatal(err)
	}
	input.GeneratedHeaders = metadata
	consumer, err := loadFeatureConsumer(ctx, writeFeatureInput(t, input), t.TempDir(), "linux/amd64", input.Module, nil)
	if err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadGeneratedHeaderPackages(consumer, []string{"."}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := consumer.capturePackages(pkgs); err != nil {
		t.Fatal(err)
	}
	if err := consumer.captureGeneratedMetadata(pkgs, nil, t.TempDir()); err != nil {
		t.Fatal(err)
	}
	// The -asmhdr oracle has completed, but LLVM objects have not. An
	// external dependency is outside the root module's source hash map.
	if err := os.WriteFile(dependency, []byte("package external\ntype Layout struct { Word uintptr }\nfunc Body() int { return 2 }\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := consumer.verifySources(); err == nil || !strings.Contains(err.Error(), "generated-header dependency") {
		t.Fatalf("dependency mutation between actual header and final object was accepted: %v", err)
	}
}
